/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as ReportIndexImport } from './routes/report/index';
import { Route as RegisterIndexImport } from './routes/register/index';
import { Route as ReportOfficerIndexImport } from './routes/report/officer/index';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const ReportIndexRoute = ReportIndexImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRoute,
} as any);

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any);

const ReportOfficerIndexRoute = ReportOfficerIndexImport.update({
  id: '/report/officer/',
  path: '/report/officer/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/register/': {
      id: '/register/';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/report/': {
      id: '/report/';
      path: '/report';
      fullPath: '/report';
      preLoaderRoute: typeof ReportIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/report/officer/': {
      id: '/report/officer/';
      path: '/report/officer';
      fullPath: '/report/officer';
      preLoaderRoute: typeof ReportOfficerIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/register': typeof RegisterIndexRoute;
  '/report': typeof ReportIndexRoute;
  '/report/officer': typeof ReportOfficerIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/register': typeof RegisterIndexRoute;
  '/report': typeof ReportIndexRoute;
  '/report/officer': typeof ReportOfficerIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/register/': typeof RegisterIndexRoute;
  '/report/': typeof ReportIndexRoute;
  '/report/officer/': typeof ReportOfficerIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/register' | '/report' | '/report/officer';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/register' | '/report' | '/report/officer';
  id: '__root__' | '/' | '/register/' | '/report/' | '/report/officer/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RegisterIndexRoute: typeof RegisterIndexRoute;
  ReportIndexRoute: typeof ReportIndexRoute;
  ReportOfficerIndexRoute: typeof ReportOfficerIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ReportIndexRoute: ReportIndexRoute,
  ReportOfficerIndexRoute: ReportOfficerIndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/register/",
        "/report/",
        "/report/officer/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/report/": {
      "filePath": "report/index.tsx"
    },
    "/report/officer/": {
      "filePath": "report/officer/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
